image: python:2.7
stages:
  # - lint
  # - sectest
    - appinspecttest
    - deploy

variables:
  AWS_DEFAULT_REGION: us-west-1 # The region of our S3 bucket
  BUCKET_NAME: gitlabpackage         # Your bucket name

# delint:
#     stage: lint
#     script:
#     - pip install pylint
#     - pylint ${CI_PROJECT_DIR}/bin/*.py
#     tags: 
#         - docker

# sectests:
#     stage: sectest
#     script:
#     - pip install bandit
#     - bandit -r ${CI_PROJECT_DIR}/bin
#     tags: 
#         - docker

appinspecttest:
    stage: appinspecttest
    before_script:
      - wget --output-document splunk-appinspect.tar.gz https://download.splunk.com/misc/appinspect/splunk-appinspect-2.0.0.tar.gz
      - pip install splunk-appinspect.tar.gz 
    script:
      - mkdir /tmp/${CI_PROJECT_NAME}
      - git archive --format tar HEAD | tar -xC /tmp/${CI_PROJECT_NAME}
      - ls /tmp/${CI_PROJECT_NAME}
      - splunk-appinspect inspect /tmp/${CI_PROJECT_NAME} --mode precert --included-tags cloud

deploy:
  stage: deploy
  before_script:
    - pip install awscli # Install the SDK
  script:
  - mkdir /tmp/package
  - git archive --format tar.gz --prefix ${CI_PROJECT_NAME}/ --output /tmp/package/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.gz HEAD
  - ls /tmp/package
  - cd /tmp/package
  - aws s3 cp ${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.gz s3://${BUCKET_NAME}/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.gz # Push app to s3 bucket
  - echo "{ \"name\":\"${CI_PROJECT_NAME} app v${CI_COMMIT_TAG}\", \"tag_name\":\"${CI_COMMIT_TAG}\", \"description\":\"Description\", \"assets\":{ \"links\":[{ \"name\":\"App\", \"url\":\"http://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.gz\" }] } }"
  - curl -v -XPOST -H "PRIVATE-TOKEN:$GITLABAPI_TOKEN" -H "Content-type:application/json" -d "{ \"name\":\"${CI_PROJECT_NAME} app ${CI_COMMIT_TAG}\", \"tag_name\":\"${CI_COMMIT_TAG}\", \"description\":\"Description\", \"assets\":{ \"links\":[{ \"name\":\"App\", \"url\":\"http://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.gz\" }] } }" "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/releases"
  environment:
    name: ${CI_COMMIT_REF_SLUG}
    url: http://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.gz  # This is the url of the bucket we saved before
  only:
    - tags